=== Anna-osh/Oshmyan_Anna_Summer/task5/data/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.5task.org/devices"
        xmlns:tns="http://www.5task.org/devices" elementFormDefault="qualified">
    <element name="devices">
        <complexType>
            <sequence>
                <element name="device" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string" />
                            <element name="critical" type="boolean" />
                            <element name="origin" type="string" />
                            <element name="types">
                                <complexType>
                                    <sequence>
                                        <element name="port" type="string" />
                                        <element name="consumption">
                                            <simpleType>
                                                <restriction base="int">
                                                    <minInclusive value="0" />
                                                    <maxInclusive value="1000" />
                                                </restriction>
                                            </simpleType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="price" type="double" />
                        </sequence>
                        <attribute name="id"  use="required">
                            <simpleType>
                                <restriction base="ID">
                                    <pattern value="[a-zA-z0-9_]+"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== Anna-osh/Oshmyan_Anna_Summer/task5/data/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.5task.org/devices" xsi:schemaLocation="http://www.5task.org/devices devices.xsd">
    <device id="d1">
        <name>Компьютер1</name>
        <critical>true</critical>
        <origin>США</origin>
        <types>
            <port>USB</port>
            <consumption>70</consumption>
        </types>
        <price>14</price>
    </device>
    <device id="d2">
        <name>Компьютер2</name>
        <critical>true</critical>
        <origin>Китай</origin>
        <types>
            <port>COM</port>
            <consumption>702</consumption>
        </types>
        <price>14.8</price>
    </device>
    <device id="d3">
        <name>Компьютер3</name>
        <critical>false</critical>
        <origin>Беларусь</origin>
        <types>
            <port>LPT</port>
            <consumption>31</consumption>
        </types>
        <price>1.4</price>
    </device>

</devices>
